### ISSUE TITLE
[Bug] 1.6.4: Change of Library path leads to error when loading library models

### ISSUE THREAD

**Issue by manavortex** [Neurolinked/MlsetupBuilder#8]
Hello there, 

first of all, thank you so much for making this tool. After I've finally managed to push past the ID-10t and correctly extract the game files, I've  been able to make my own recolours instead of constantly bugging other people about it. Also, I've noticed new and better features with every consecutive release, so thank you for the good work!

I actually solved my own problem while writing up this bug report for you, but then, I work in IT, but I figured I'd file a bug report anyway, since the behaviour changed with version 1.6.2 and I needed far too long to get behind this.

```
The 3dmodel wasn't there when i try to load it : \base\characters\garment\gang_monk\torso\t2_135_jacket__monk_shirt\t2_135_wa_jacket__monk_shirt.glb
No Normal, reset to safeNorm
An error happened during the load of the file: D:\_Cyberpunk_uncooked_files\base\base\characters\garment\gang_monk\torso\t2_135_jacket__monk_shirt\textures\ml_t2_135_wa_jacket__monk_shirt_masksset_0.dds
```
I can think of two things you could do to prevent people from running into this bug (and bothering you about it), if you care to do it:
- validate the path to the extracted files (if it doesn't contain at least a child folder "base", show an error message or something")
- display a clearer error message about what folder the tool is looking in ("Looking for files under **YOUR_LIBRARY_PATH\base**, please check your preferences")
- iterate up the tree and check which folder is the first one that doesn't exist ("D:\_Cyberpunk_uncooked_files\base\base doesn't exist, please check your preferences")

… if not, a good "RTFM" would probably have solved my problem, I was mostly misled by the fact that it worked under <1.6.2 and then suddenly stopped, so I assumed that maybe the relative paths didn't resolve properly anymore.

Another point of feedback: Would it be possible to make the error display the full error message rather than truncating it, or immediately opening the console after closing the popup? It took me far longer than it should have to find it (which is on me, not on you). 

I have a few suggestions/feature requests, are you interested to hear them, or should I shove it? 

Regards, and thanks again
~mana

**Comment by Neurolinked** [comment]
I will take your idea in consideration, don't worry.
Even if the version says 1.6.5 at tonight, the software it's still in a sort of beta version since i haven't stabilized all the features and the more i use it the more i see i have some needs with it.
I remember, in a later version i added an autofix for the path, but still it's right that i don't have a proper check of that folder.
Actually I'm thinking about changing the way it work with the loose files to get in some way rid of the 20GB of materials stashed in the HD of the peoples
If you wanna to be updated frequantly, i use this thread on the CP77 discord community to show the development of the features of the software
https://discord.com/channels/705931815109656596/939510887188947014

**Comment by Neurolinked** [comment]
I fixed the path error to give a better feedback, but i forgot an important things, in the first place the base the folder can't be there, why ? because MlsetupBuilder using WolvenkitCLI can extract the needed files. Anyway i will think a way to work in a different way the source uncooked folder
